[profile.default]
src = "src"
out = "out"
libs = ["../../lib"]
allow_paths = ['../../lib','../../node_modules','../../']
remappings = [
    "ds-test/=../../lib/forge-std/lib/ds-test/src/",
    "forge-std/=../../lib/forge-std/src/",
    "openzeppelin-contracts/=../../lib/openzeppelin-contracts"
]
optimizer = true
optimizer-runs = 5

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
